[package]
name = "gainesvillemls-scraper-rust"
version = "0.1.0"
authors = ["Andrew Crites <ajcrites@gmail.com>"]

[dependencies]
kuchiki = {version = "0.3.1", features = ["hyper"]}
hyper = "0.7.2"
regex = "0.1.54"
